[package]
name = "bulletproofs"
version = "0.1.0"
edition = "2024"

[dependencies]
bulletproofs = "5.0.0"
curve25519-dalek = { version = "4.1.3", features = ["serde", "rand_core"] }
merlin = "3.0.0"
sha3 = "0.10.8"
rand = "0.8.5"
rand_core = "0.6.4"
bincode = "1.3.3"
memory-stats = "1.2.0"
